"use client";

export const VOICE = {
  welcome: "welcome.mp3",
  menuSubtitle: "menu_subtitle.mp3",
  q1Start: "q1_start.mp3",
  q1Instruction: "q1_instruction.mp3",
  correct: "correct.mp3",
  wrong: "wrong.mp3",
  q1Done: "q1_done.mp3",
  q1Learned: "q1_learned.mp3",
  summary: "summary.mp3",
  summaryBias: "summary_bias.mp3",
  summaryLearned: "summary_learned.mp3",
  q3Start: "q3_start.mp3",
  q3Done: "q3_done.mp3",
  q3Retrain: "q3_retrain.mp3",
  q3Learned: "q3_learned.mp3",
  q4Start: "q4_start.mp3",
  q4Save: "q4_save.mp3",
  q4Crash: "q4_crash.mp3",
  q4AiRight: "q4_ai_right.mp3",
  q4FalseAlarm: "q4_false_alarm.mp3",
  q4Done: "q4_done.mp3",
  q4Learned: "q4_learned.mp3",
  q5Start: "q5_start.mp3",
  q5Launch: "q5_launch.mp3",
  q5Step1: "q5_step1.mp3",
  q5Step2: "q5_step2.mp3",
  q5Step3: "q5_step3.mp3",
  q5Step4: "q5_step4.mp3",
  q5Step5: "q5_step5.mp3",
  q5Done: "q5_done.mp3",
  q5Learned: "q5_learned.mp3",
  allDone: "all_done.mp3",
};
